### PR TITLE
Incorporate non-binary identifiers for sex and gender

### PR DESCRIPTION
**Pull request by mattsigal**
Added sexNB() and genderNB().  Since sex and gender are different
concepts (with different levels), they both hijack r_sample_faction
rather than one to the other.  sexNB() might be expanded in the future
to include options: MtF Female and FtM Male (see
http://itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-qu
estion-on-an-application-form-more-inclusive/)

### CODE REVIEW

**Comment by trinker** [comment]
@mattsigal Thanks for the pull request.  I like everything except the name.  I'm trying to make names of functions be meaningful, underscore separated, and not overly lengthy if possible.  I was thinking something more like:

```r
sex_inclusive
gender_inclusive
```

but correct terminology to describe "inclusive" is outside of my expertise.  Is it acceptable terminology and meaningful to use `_inclusive`?

Also you said:

> sexNB() might be expanded in the future to include options: MtF Female and FtM Male 

I'd prefer to do that now rather than later if this would be expected in social sciences?  If you agree could you include these groups as well with the appropriate proportion?

**Comment by mattsigal** [comment]
@trinker No problem, and yeah - no worries about changing the name.  I should have looked at the other function names and followed the package style ;)

I believe `_inclusive` would be acceptable, so would `identified_sex` and `identified_gender`.  Which do you prefer?

Regarding the other comment, the reason I didn't include the other two categories is that I do not have any idea about the appropriate proportions to use (at the moment, the statistic I used for intersex is actually based upon the estimated proportion of transgender, which are quite different things).  If we keep the proportion of the non male/female categories constant, we could simply divide that into three - but again, this would be a very, very rough estimate.  But, I agree that it would be nice to include now even with that problem, and whenever research catches up it could always be modified.

**Comment by trinker** [comment]
There was a merge with caution on this pull request so I manually added your work.  I added you as a contributor.  Thanks for the pull request.

https://github.com/trinker/wakefield/blob/master/R/sex_inclusive.R

**Comment by mattsigal** [comment]
Excellent!  Yeah, I noticed the Travis warning, and I think it was because I created the new R files but didn't redocument the package, so it was missing the Rd files?

**Pull request closed without merging**
